#!/bin/bash
Ip="${1:-}"
Loop=1
options=(
 "Functions of system"
 "Apps" 
 "Free search"
 "Exit"
)
app_options=(
    "Netflix"
    "Spotify"
    "Youtube" 
    "Prime Video" 
    "Disney+" 
    "Pluto TV" 
    "Close Apps" 
    "Return to menu"
)
