#!/bin/bash
Loop=1
Ip="192.155.4.108"
system_choice=0
options=(
 "Functions of system"
 "Apps" 
 "Free navigation"
 "Exit"
)
app_options=(
    "Netflix"
    "Spotify"
    "Youtube" 
    "Prime Video" 
    "Disney+" 
    "Pluto TV" 
    "Close Apps" 
    "Return to menu"
)
